version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: notifications-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 985156280Aa!
      MYSQL_DATABASE: notifications_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - notifications-net

  activemq:
    image: rmohr/activemq:latest
    container_name: notifications-activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    networks:
      - notifications-net

volumes:
  mysql_data:

networks:
  notifications-net:
